env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

install: true
before_script:
- sudo apt update -y >/dev/null 2>&1 || true
- sudo apt install -y --no-install-recommends curl bash tree python-pip >/dev/null 2>&1
- sudo pip install httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 3000 8080

script:
- export root=$(pwd)
- |
  for project in \
      frontend-ng \
      frontend-vue \
      frontend-nuxt \
      frontend-react \
  ; do
      cd ${root}/${project}
      bash gradlew >/dev/null
  done

- tree ${root}/local-maven-repo/daggerok

- cd ${root}/backend
- >
  for id in ng vue nuxt react; do
    cp -Rf build-${id}.gradle build.gradle
    cp -Rf settings-${id}.gradle settings.gradle
    bash gradlew >/dev/null
    bash build/libs/backend-${id}*.jar &
    wait_for 8080
    http :8080
    stop_any 80 3000 8080
  done

cache:
  directories:
  - ui/node_modules
  - $HOME/.gradle
  - $HOME/.m2
